version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./api:/app
    ports:
      - "80:80"
    # env_file:
    #   - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: categories
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
